### ISSUE TITLE
Remove telegram support button

### ISSUE THREAD

**Issue by SanghamitraBhowmick1993** [MXCzkEVM/datadash-wallet#184]
https://www.notion.so/wannsee-roadmap/Remove-telegram-support-button-7190d6621e394040aef1bd2cce03d75d

**Comment by reasje** [comment]
@SanghamitraBhowmick1993 Thanks for mentioning, I think I don't have any to do in this ticket.

**Comment by sheenhx** [comment]
yes it is hairy

**Comment by SanghamitraBhowmick1993** [comment]
as per my understanding this was already tested and only PR merges were pending. Assuming, the PRs are merged, moving this to DONE
