### ISSUE TITLE
Increasing IOS version for upcoming builds

### ISSUE THREAD

**Issue by reasje** [MXCzkEVM/datadash-wallet#193]
I will need to update the following for upcoming releases, 
1. My dev environment 
2. Project target IOS SDK
3. Flutter version might be required to be updated 
4. Packages also might be required to be updated 
5. App center build props 

![Image](https://github.com/MXCzkEVM/datadash-wallet/assets/53487920/2620224d-eb67-4808-8a70-83297707015b)

**Comment by reasje** [comment]
I have made ready the local dev env, Tested on It, It worked fine I have updated app center build settings.

**Comment by reasje** [comment]
According to this https://xcodereleases.com/
I have updated My Mac Xcode and ios 17.2 simulators

**Comment by reasje** [comment]
The main branch includes the build with ios 17.2 compatibale version 
https://appcenter.ms/orgs/MXC-Foundation-gGmbH/apps/DD-Wallet-iOS/build/branches/main/builds/406
@SanghamitraBhowmick1993

**Comment by SanghamitraBhowmick1993** [comment]
This is working and the submission is approved https://appstoreconnect.apple.com/apps/6460891587/distribution/reviewsubmissions/details/e27e7b81-8052-4b9d-a2b5-ab5ddf7f915c
